export const ADD_TO_CARRITO = "ADD_TO_CARRITO";
export const REMOVE_ONE_CARRITO = "REMOVE_ONE_CARRITO";
export const REMOVE_ALL_CARRITO = "REMOVE_ALL_CARRITO";
export const LIMPIEZA_CARRITO = "LIMPIEZA_CARRITO";
