export const TYPES = {
    ADD_TO_CARRITO: "ADD_TO_CARRITO",
    REMOVE_ONE_CARRITO: "REMOVE_ONE_CARRITO",
    REMOVE_ALL_CARRITO: "REMOVE_ALL_CARRITO",
    LIMPIEZA_CARRITO: "LIMPIEZA_CARRITO",
  };
  